#ifndef _lpc17xx_hal_h_
#define _lpc17xx_hal_h_

#ifdef __cplusplus
extern "C" {
#endif

#include "LPC17xx.h"
#include "i2s_lpc17xx.h"
#include "tim_lpc17xx.h"
#include "uart_lpc17xx.h"
#include "clock_lpc17xx.h"

#define SET_BIT(REG, BIT)       ((REG) |= (BIT))
#define CLEAR_BIT(REG, BIT)     ((REG) &= ~(BIT))

#define PCONP_SPI_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCSPI)
#define PCONP_SSP0_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCSSP0)
#define PCONP_SSP1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCSSP1)
#define PCONP_UART0_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART0)
#define PCONP_UART1_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART1)
#define PCONP_UART2_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART2)
#define PCONP_UART3_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCUART3)
#define PCONP_I2S_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCI2S)
#define PCONP_GPDMA_ENABLE    SET_BIT(LPC_SC->PCONP, SC_PCONP_PCGPDMA)
#define PCONP_ADC_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCADC)
#define PCONP_TIM0_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM0)
#define PCONP_TIM1_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM1)
#define PCONP_TIM2_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM2)
#define PCONP_TIM3_ENABLE     SET_BIT(LPC_SC->PCONP, SC_PCONP_PCTIM3)
#define PCONP_RIT_ENABLE      SET_BIT(LPC_SC->PCONP, SC_PCONP_PCRIT)


#define DBG_PIN_MASK    (1 << 28)
//LPC_PINCON->PINSEL3 &= (3 << 26); LPC_GPIO1->FIODIR |= DBG_PIN_MASK
#define DBG_PIN_LOW     LPC_GPIO1->FIOCLR = DBG_PIN_MASK
#define DBG_PIN_HIGH    LPC_GPIO1->FIOSET = DBG_PIN_MASK
#define DBG_PIN_TOGGLE  LPC_GPIO1->FIOPIN ^= DBG_PIN_MASK

#define USER_LED_MASK   (1<<29) //P1.29 (D8 BLUE)
#define USER_LED_ON     LPC_GPIO1->FIOSET = USER_LED_MASK
#define USER_LED_OFF    LPC_GPIO1->FIOCLR = USER_LED_MASK
#define USER_LED_TOGGLE LPC_GPIO1->FIOPIN ^= USER_LED_MASK

#define DBG_PIN_INIT    LPC_GPIO1->FIODIR |= DBG_PIN_MASK | USER_LED_MASK

#ifdef __cplusplus
}
#endif

#endif